### ISSUE TITLE
Circular import error 

### ISSUE THREAD

**Issue by kfertakis** [mindspore-lab/mindrlhf#21]
Hi,

I'm getting a circular import error when running `train.py` with default configurations.

`ImportError: cannot import name 'CausalLMHydraWithValueHead' from partially initialized module 'mindrlhf.models.ppo_models' (most likely due to a circular import) (~/mindrlhf/models/ppo_models.py)`

Any idea how to remedy this? Thanks. 

mindspore version: 2.0.0
mindformers  version: 2023.9.dev0
commit 40743db3e5e2ea1af34c2d36c3f86d86be541462

**Comment by ChessQian** [comment]
Maybe you can try the latest master branch.

**Comment by kfertakis** [comment]
yeap, the issue seems to be resolved in the latest version. Thanks.
