### ISSUE TITLE
Support for gpt2

### ISSUE THREAD

**Issue by kfertakis** [mindspore-lab/mindrlhf#32]
Hi,

GPT2 is supported based on the documentation and previous working version of mindrlhf. However, in the latest code, there is a [hardcoded check](https://github.com/mindspore-lab/mindrlhf/blob/5fb12735398acf19aea95dcc9e263b9d62687635/mindrlhf/models/ppo_models.py#L118) allowing only pangu and bloom models. How can we enable gpt2 training? 

Thanks

Commit: [5fb1273](https://github.com/mindspore-lab/mindrlhf/commit/5fb12735398acf19aea95dcc9e263b9d62687635)

**Comment by ChessQian** [comment]
GPT2：https://github.com/mindspore-lab/mindrlhf/pull/33
