### ISSUE TITLE
single prompt being used in training 

### ISSUE THREAD

**Issue by kfertakis** [mindspore-lab/mindrlhf#52]
Hi, 

currently the code seems to be hardcoded to use only `num_rollouts`(configured to 1 [here](https://github.com/mindspore-lab/mindrlhf/blob/ce81d4fcaa9dc82a64d4b4ffcf2890d96707c03d/mindrlhf/configs/ppo_configs.py#L29)) for training, regardless of the number of epochs, as can be seen in the `prompt_dataloader` creation in `PPOTrainer` ([here](https://github.com/mindspore-lab/mindrlhf/blob/ce81d4fcaa9dc82a64d4b4ffcf2890d96707c03d/mindrlhf/trainer/ppo_trainer.py#L82)). Is there a reason why? Also why is `num_rollouts` configured to 1? Thanks

**Comment by ChessQian** [comment]
hi，now it supports to change the default config in ppo_configs. In the future, the `ppo_config` will be converted to a yaml file, and users can change the configs in a yaml file
