### ISSUE TITLE
LLAMA2在Nvidia GPU 上无法运行

### ISSUE THREAD

**Issue by zhz44** [mindspore-lab/mindrlhf#72]
以下为错误信息， 运行环境是 mindspore 2.10, mindformers 1.10(dev branch), GPU, Nvidai a6000. 

Traceback (most recent call last):
  File "/home/hz04/mindrlhf/train.py", line 103, in <module>
    run_rlhf(args)
  File "/home/hz04/mindrlhf/train.py", line 93, in run_rlhf
    trainer.make_experience(num_rollouts=ppo_config.num_rollouts)
  File "/home/hz04/mindrlhf/mindrlhf/trainer/ppo_trainer.py", line 239, in make_experience
    samples, resposne_array, left_padding_prompt = self.generate(prompt_tensors)
  File "/home/hz04/mindrlhf/mindrlhf/trainer/ppo_trainer.py", line 191, in generate
    outputs = self.ppo_model.policy_model.model.generate(input_ids_list, max_new_tokens=self.ppo_config.max_decode_length)
  File "/home/hz04/.local/lib/python3.9/site-packages/mindformers/generation/text_generator.py", line 1130, in generate
    output_ids = self._greedy_search(
  File "/home/hz04/.local/lib/python3.9/site-packages/mindformers/generation/text_generator.py", line 397, in _greedy_search
    res = self._incremental_infer(
  File "/home/hz04/.local/lib/python3.9/site-packages/mindformers/generation/text_generator.py", line 226, in _incremental_infer
    res = self(
  File "/home/hz04/.local/lib/python3.9/site-packages/mindspore/nn/cell.py", line 680, in __call__
    out = self.compile_and_run(*args, **kwargs)
  File "/home/hz04/.local/lib/python3.9/site-packages/mindspore/nn/cell.py", line 1020, in compile_and_run
    self.compile(*args, **kwargs)
  File "/home/hz04/.local/lib/python3.9/site-packages/mindspore/nn/cell.py", line 997, in compile
    _cell_graph_executor.compile(self, phase=self.phase,
  File "/home/hz04/.local/lib/python3.9/site-packages/mindspore/common/api.py", line 1547, in compile
    result = self._graph_executor.compile(obj, args, kwargs, phase, self._use_vm_mode())
ValueError: For BatchMatMul, inputs shape cannot be broadcast on CPU/GPU, with x shape [const vector]{1, 32, 2048, 128}, y shape [const vector]{128, 128}

- C++ Call Stack: (For framework developers)
mindspore/core/ops/batch_matmul.cc:119 CheckBatchMatmulInputWhetherCanBeBroadcast

- The Traceback of Net Construct Code:

#0 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:450
        if self.use_past:
#1 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:451
            if not isinstance(batch_valid_length, Tensor):
#2 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:453
        if self.training:
#3 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:456
            tokens = input_ids
            ^
#4 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:459
        if not self.is_first_iteration:
#5 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:463
        if pre_gather:
#6 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:461
        output = self.model(tokens, batch_valid_length, batch_index, zactivate_len, block_tables, slot_mapping)
                 ^
#7 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:266
        if not self.use_past:
#8 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:272
            if self.is_first_iteration:
#9 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:273
                freqs_cis = self.freqs_mgr(seq_len)
                ^
#10 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:272
            if self.is_first_iteration:
#11 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:461
        output = self.model(tokens, batch_valid_length, batch_index, zactivate_len, block_tables, slot_mapping)
                 ^
#12 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:293
        for i in range(self.num_layers):
#13 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama.py:294
            h = self.layers[i](h, freqs_cis, mask, kvcache_inputs=kvcache_inputs)
                ^
#14 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_transformer.py:564
        h = self.attention(input_x, freqs_cis, mask, kvcache_inputs)
            ^
#15 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_transformer.py:280
        if self.qkv_concat:
#16 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_transformer.py:290
            query = self.cast(self.wq(x), self.dtype)  # dp, 1 -> dp, mp
            ^
#17 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_transformer.py:294
        if self.use_past and not self.is_first_iteration:
        ^
#18 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_transformer.py:299
            query = self.reshape(query, (bs, seq_len, self.n_head, self.head_dim))
            ^
#19 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_transformer.py:309
        if self.use_past:

#20 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_transformer.py:315
                key, value = self.kvcache_mgr(key, value, kvcache_inputs)
                ^
#21 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_transformer.py:320
        if self.use_flash_attention:
#22 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_transformer.py:328
                attention = self._attn(query, key, value, mask)
                ^
#23 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_transformer.py:307
        query, key = self.apply_rotary_emb(query, key, freqs_cis)  # dp, mp, 1, 1
                     ^
#24 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_layer.py:247
        if self.use_rope_slice:
#25 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_layer.py:253
            xq_out = self.add(mul(xq, freqs_cos),
#26 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_layer.py:254
                              mul(self.rotate_half(xq, swap_mask), freqs_sin))
                                  ^
#27 In file /home/hz04/.local/lib/python3.9/site-packages/mindformers/models/llama/llama_layer.py:229
        x = self.bmm_swap(x, swap_mask)
            ^
 (See file '/home/hz04/mindrlhf/rank_0/om/analyze_fail.ir' for more details. Get instructions about `analyze_fail.ir` at https://www.mindspore.cn/search?inputValue=analyze_fail.ir)

**Comment by ChessQian** [comment]
目前只支持NPU，暂不支持GPU
